### ISSUE TITLE
Feature Request Add support for --host option to gather metrics

### ISSUE THREAD

**Issue by saltyautomation** [cordelster/mesh-metrics#6]
It would be great if we could use the built in wifi on esp32 devices to gather these metrics without having to have the dedicated USB connection. the meshtastic CLI supports using the --host flag to connect to a radio that has wifi enabled. I can possibly modify the script for my needs but would like to see it added to your upstream. Happy to beta test this as well and provide feedback. 

https://meshtastic.org/docs/software/python/cli/
--host HOST

The hostname/ipaddr of the device to connect to (over TCP).

Usage
meshtastic --host HOST

Thanks!

**Comment by cordelster** [comment]
I will add this option.

**Comment by kevinelliott** [comment]
I second this, looking forward to it. Thank you @cordelster !

**Comment by cordelster** [comment]
I have pushed to associated issue branch changes. See if they work for you. Added "-m ip" for method, use "-p 192.168.x.x" for your device IP.
./mesh_metrics.sh -f example.lst -p 192.168.120.5  -m ip

https://github.com/cordelster/mesh-metrics/tree/6-feature-request-add-support-for-host-option-to-gather-metrics
